version: "3"
services:
    lv:
        image: lv_dev
        hostname: ${APP_HOSTNAME:-lv}
        build:
            context: .
            target: development
            args:
                WWWGROUP: "${WWWGROUP}"
        ports:
            - ${APP_PORT:-80}:80
            - ${VITE_DS_PORT:-3000}:${VITE_DS_PORT:-3000}
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ./:/var/www/html
            - ${NPM_CACHE:-/var/www/html/npm/cache}:/root/.npm
        networks:
            - sail

    mailhog:
        image: "mailhog/mailhog:latest"
        hostname: ${FORWARD_MAILHOG_HOSTNAME:-mailhog}
        ports:
            - "${FORWARD_MAILHOG_PORT:-1025}:1025"
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail

networks:
    sail:
        external: true
        name: lv_network

volumes:
    sailmeilisearch:
        driver: local
